version: "3"
services:
  logovote-client:
    build:
      context: ./client
      args:
        ROOT_URL: www.eth.taipei
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '0.1'
    restart: on-failure
  logovote-server:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - FULLNODE_URL=fullnode
      - NODE_ENV=production
    links:
      - fullnode
    deploy:
      resources:
        limits:
          cpus: '0.4'
    restart: on-failure
  fullnode:
    image: parity/parity:beta
    volumes:
      - ./mnt/:/root/.local/share/io.parity.ethereum/
    command: "--no-ui --no-ancient-blocks --jsonrpc-cors '*' --jsonrpc-interface 'all' --jsonrpc-hosts 'all'"
    deploy:
      resources:
        limits:
          cpus: '0.4'
    restart: on-failure