version: "2"
services:
  logovote-client:
    build:
      context: ./client
      args:
        ROOT_URL: 0.0.0.0
    ports:
      - 5000:5000
  logovote-server:
    build: ./server
    ports:
      - 3000:3000
    environments:
      - FULLNODE_URL: fullnode
    links:
      - fullnode
  fullnode:
    image: parity/parity:beta
    volumes:
      - ./mnt/:/root/.local/share/io.parity.ethereum/
    command: "--jsonrpc-cors '*' --jsonrpc-interface 'all' --jsonrpc-hosts 'all'"
